import com.google.gson.Gson;
import model.FirebaseResponse;
import model.FirebaseUID;
import service.FirebaseSvc;
import java.io.IOException;
import java.util.LinkedHashMap;

public class Examples {

    public static void main(String[] args) {

        // change to your firebase reference url
        String FIREBASE_REF = "https://smartplayTest.firebaseio.com/";

        // Create firebase reference with Full logging. Make sure you set to false in production
        FirebaseSvc fbSvc = new FirebaseSvc(FIREBASE_REF,true);

        // examples

        try {
            // Delete
            // The example below Deletes the root (clears data from previous tests)
            fbSvc.delete("");

            // There are three ways you can pass data to PUT POST and PATCH requests:
            // 1- pass the path and an object (could be a class you have defined or a data structure)
            // 2- pass the path and a MAP object
            // 3- pass the path and raw json data

            // PUT request passing path and an object
            // Object to be passed
            UserDetails user1 = new UserDetails("uid1",100,150,70, "I love travel and discovering new cultures");
            fbSvc.put("userDetails/uid1",user1);

            // PUT request passing raw json data
            // let's add another user
            String rawjson = "{\"userUID\":\"uid2\",\"nb_followers\":\"4000\",\"nb_following\":\"1000\",\"nb_posts\":\"300\"}";
            fbSvc.put("userDetails/uid2",rawjson);

            // PATCH request passing a MAP
            // Let's add bio information to the user we just added (uid2)
            LinkedHashMap<String, Object> datamap = new LinkedHashMap<String, Object>();
            datamap.put("bio", "Musician/Band");
            fbSvc.patch("userDetails/uid2",datamap);

            // POST
            // User uid1 posts a photo, let's save the info
            datamap.clear();
            datamap.put("description","Enjoying this beautiful sunset, where are you traveling next?");
            datamap.put("imageLink","https://myclouddatastorage/image231");
            FirebaseResponse response = fbSvc.post("userPosts/uid1",datamap);

            // Firebase generates a unique ID for each post request and returns it in the response
            // Below is a sample code in case you need to retrieve this unique ID from the FirebaseResponse
            // body field - which will contain a json string in the form of {"name":"<firebase unique id>"}
            // ex: {"name":"-L8v6-NuOg_9W6feuE6y"}

            FirebaseUID firebaseUID;

            if (response.isSuccess()) {
                Gson gson = new Gson();
                firebaseUID = gson.fromJson(response.getBody(), FirebaseUID.class);
                System.out.println("Unique ID generated by firebase for this POST request : " + firebaseUID.getName());

                // someone comments on the photo, let's save the comment under the node we just generated above
                datamap.clear();
                datamap.put("comment","Amazing shot!");
                fbSvc.post("userPosts/uid1/" + firebaseUID.getName() + "/comments",datamap);

            }
            

            //UserDetails user2 = new UserDetails("uid2",4000,1000,300, "Musician/Band");
            // LinkedHashMap<String, Object> datamap = new LinkedHashMap<String, Object>();
            // user2.put("uid2",)
            // deletes the key and everything under it
            // firebaseResponse = fbSvc.delete("users/-KvcV06UQENpcyPdzCKm");

        }

        catch (IOException e) { // Network error
            System.out.println("Network error " + e );

        }
        catch (Exception e) { // Unexpected/parse error
            System.out.println("Unexpected/parse error " + e );

        }

    }

}
