/**
 * Created by raniamakki on 9/15/17.
 */
public class UserF {

    // Key Generated by firebase
    private String userId;

    private String userName;
    private String password;

    public UserF() {
    }

    public UserF(String userName,String password) {
        super();
        this.userName = userName;
        this.password = password;
    }


    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;}

    public void setPassword(String password ) {
        this.password = password;
    }

}